# -*- mode: Makefile -*-
test: test_ohi_latex test_anemone
	make -f Makefile.pypi test
	@echo All tests passed
test_ohi_latex:
	echo kǎoyàn|python2.7 ohi_latex.py --dry-run
	grep '\\kao3\\yan4' index.tex >/dev/null
	echo kǎoyàn|python3 ohi_latex.py --dry-run
	grep '\\kao3\\yan4' index.tex >/dev/null
test_anemone:
	ruff check anemone.py
	python3 -m pytest test_anemone.py
.PHONY: test test_ohi_latex test_anemone
